# Generated by Django 5.1.4 on 2025-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Cricket', 'Cricket')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
    ]
