# Generated by Django 5.1.4 on 2025-01-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_sportsschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='command',
            field=models.CharField(choices=[('Western Command', 'Western Command'), ('Central Command', 'Central Command'), ('Eastern Command', 'Eastern Command'), ('Southern Command', 'Southern Command'), ('Southern Western Command', 'Southern Westren Command')], max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Inter Batallion', 'Inter Batallion'), ('Inter Division', 'Inter Division'), ('Inter Corps', 'Inter Corps'), ('Inter Command', 'Inter Command')], max_length=200),
        ),
    ]
