# Generated by Django 5.1.4 on 2025-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='command',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
